rvm:
  - 2.5.1
language: ruby

services:
  - postgres:latest

before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres

rspec:
  script:
    - bundle exec rspec
